### ISSUE TITLE
brew & pip dual sip installation caused segfault

### ISSUE THREAD

**Issue by tlambert03** [maweigert/spimagine#14]
This is not a spimagine problem, but I just wanted to make a note in case anyone else has the issue I just came across:

On two seperate OS X (sierra) systems I just tested, I was getting a segmentation fault crash with trying to directly run spimagine from the command line or when importing spimagine in a python interpreter.  In a python2 environment I got segfaults, in python3, it didn't segfault, but it failed to import.  I was able to narrow it down to a problem with PyQt5 trying to import sip... On my system i had already installed sip through homebrew, and it turned out installing spimagine and PyQt5 also installed sip through pip, and those two conflicted.  Running `brew uninstall sip` solved the segfault and allowed me to use spimagine in both Py2 and Py3 on my system

thanks for a great package!

**Comment by maweigert** [comment]
Hi Talley, 

thanks for the hint. One of the reasons I switched from PyQt4 to PyQt5 was that there is a reasonable pypi version for the latter (only python3 though) which removes the need for installing pyqt via e.g. homebrew (which for me always took ages and was full of pain). 
Good to know that the brew sip is not compatible with the pqyt5 from pypi... 
Thanks for the report!
