### ISSUE TITLE
mouse wheel controls both slice position and zoom in the slice widget

### ISSUE THREAD

**Issue by tlambert03** [maweigert/spimagine#19]
would be great to have finer-tuned control over the exact roi being shown in the slice widget.

**Comment by maweigert** [comment]
Thanks. Somehow the wheelevent was still captured by the slider, which it should not. 
Fixed in develop now. 

- mouse wheel now zooms into the slice
- left mouse pressed will move the displayed region
- left click on ("x","y","z") next to the slider cycles through the axis.
