### ISSUE TITLE
Can this tool work with an NVIDA GPU?

### ISSUE THREAD

**Issue by WeisongZhao** [maweigert/spimagine#32]
Can this tool work with an NVIDA GPU? Because I have no AMD GPU. 
By the way, the video (i.e. 2) of this paper 'Content-aware image restoration: pushing the limits of fluorescence microscopy' is really amazing! Could you tell me how you made these awesome videos?

**Comment by maweigert** [comment]
Hi Weison,

Sure, it works on Nvidia GPUs too! (In fact, most of my machines have only a Nvidia GPU). You have to make sure that OpenCL is working, though, see 
https://github.com/maweigert/spimagine#verify-the-availability-of-opencl-1

And glad you like the video! The one you mention uses the `OverlayData` class that comes with spimagine, which creates overlay stacks from two given 3D volumes. A simple example demonstrating this is the following:

```python 
import numpy as np
from spimagine import volshow
from spimagine import OverlayData

# create two example stacks - a sphere in the middle and a noisy version 
N = 256
Xs = np.mgrid[:N,N//4:3*N//4,:N]-N/2
R = np.sqrt(np.sum(Xs**2, axis= 0))
img_clean = 100.*((np.exp(-20*R**2/N**2))+(R<N/4))
img_noisy = .8*img_clean + 40*np.random.normal(0,1,img_clean.shape)

# display it as an overlay (i.e. slipping through time changes the overlap) 
volshow(OverlayData(img_noisy, img_clean))
```
which should result in this: 

![overlay](https://user-images.githubusercontent.com/11042162/52073752-95c4e680-2588-11e9-84aa-c3347f38f910.png)

Hope this helps!

Martin

**Comment by maweigert** [comment]
Btw, I just created a new version for pypi, so you need to reinstall the latest version  (`0.2.6`) for the example above.

**Comment by maweigert** [comment]
Sure, OpenCL support should be included via the normal Nvidia drivers
https://developer.nvidia.com/opencl
Best is to check with `clinfo` (which you might have to install first).
Let me know if something doesn't work!

**Comment by WeisongZhao** [comment]
Many thanks.
