### ISSUE TITLE
Error starting spimagine...Non-empty compiler/cannot load Qt

### ISSUE THREAD

**Issue by LencEz** [maweigert/spimagine#36]
Hi,
I'm trying to run spimagine on Ubuntu 20.04 with python3. When I run spimagine I get the following error...

> /usr/lib/python3/dist-packages/pyopencl/__init__.py:233: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

> Aborted (core dumped)

Any thoughts or help would be wonderful. I'm running the amd OpenCL drivers for ubuntu 20.04. I'm new to OpenCl, but they look like they are installed correctly based on the clinfo output.
Thanks!

**Comment by maweigert** [comment]
Hi @LencEz ,

could you try running it like that

`QT_DEBUG_PLUGINS=1 spimagine` 

and post the output?

**Comment by LencEz** [comment]
Hi @maweigert 
Thanks for the quick reply! I'm wondering I didn't get openCL installed correctly. I might try uninstalling and then reinstalling. Here is the output from what you asked:

>/usr/lib/python3/dist-packages/pyopencl/__init__.py:233: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
>QFactoryLoader::QFactoryLoader() checking directory path "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms" ...
>QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqminimal.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqvnc.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-egl.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archreq": 0,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("wayland-egl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-generic.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archreq": 0,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("wayland")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-egl.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-egl"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("wayland-xcomposite-egl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-glx.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-glx.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-glx"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeGlxPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("wayland-xcomposite-glx")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwebgl.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqwebgl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "webgl"
        ]
    },
    "archreq": 0,
    "className": "QWebGLIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("webgl")
QFactoryLoader::QFactoryLoader() looking at "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


>Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
Cannot load library /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
>This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

>Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

>Aborted (core dumped)

**Comment by tlambert03** [comment]
looks like you're missing the `libxcb-xinerama.so.0` shared library:

> "Cannot load library /usr/local/lib/python3.8/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-xinerama.so.0: cannot open shared object file: No such file or directory)"

try:
```
sudo apt-get update
sudo apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev
```

more info here: https://forum.qt.io/topic/116299/qt-creator-ubuntu-20-04/20

**Comment by LencEz** [comment]
That fixed it. Thanks @tlambert03 !! Looks amazing!

**Comment by maweigert** [comment]
Thanks @tlambert03 :)
