### ISSUE TITLE
can we use Spimagine on Windows?

### ISSUE THREAD

**Issue by buratono** [maweigert/spimagine#5]
Hi,
I read the spimagine docs I see that it works on Mac and Linux.
How is about Windows platform?
Any hint?
Thanks,
Tom

**Comment by maweigert** [comment]
Should be running on windows likewise (it does here on a windows 7 workstation).
Requirements are the same:
1) OpenCL 
2) pyopencl / PyQt4 (I used the prebuilt binaries from http://www.lfd.uci.edu/~gohlke/pythonlibs/ )  

Hope that helps,
Martin

**Comment by buratono** [comment]
Hi Martin,
Thank for your reply,
I follow your instructions, at the final step, to install spimagine, I got the following problem
(I use Anaconda python 2.7, Windows 7)
![spimagine_install_error](https://cloud.githubusercontent.com/assets/7944081/9873095/d164ba98-5b9d-11e5-8863-e11c17e23f17.JPG)

I try below suggestion, but it didn't help,
https://github.com/maweigert/spimagine/issues/7

Can somebody help?
Thanks,
Tom

**Comment by buratono** [comment]
I fixed this bug:
in file "setup.py", section "package_data":
'data/' should be corrected to 'data/*'

However, when I run samples I got another error:

Traceback (most recent call last):
  File "D:\Dropbox\Works\ectrack\spimagine\volume_renderer.py", line 40, in <module>
    from gputools import init_device, get_device, OCLProgram, OCLArray, OCLImage
  File "C:\Anaconda\lib\site-packages\gputools-0.1.1-py2.7.egg\gputools\__init__.py", line 1, in <module>
    from gputools.core.config import init_device, get_device
  File "C:\Anaconda\lib\site-packages\gputools-0.1.1-py2.7.egg\gputools\core\config.py", line 5, in <module>
    import pyopencl
  File "C:\Anaconda\lib\site-packages\pyopencl\__init__.py", line 30, in <module>
    import pyopencl._cl as _cl
ImportError: DLL load failed: La procédure spécifiée est introuvable.

Can anyone help?
Thanks
Tom

**Comment by maweigert** [comment]
Hey Tom, 

1) thanks for the hint within package_data, i fixed it and its now in the main repo.

2) the ImportError is related to pyopencl not being installed correctly (which is a requirement).
Did you install it via http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl   ?
If so, see if 

$python -c "import pyopencl"

runs without error. If not, you might have to reinstall your nvidia sdk/opencl environment.

hope that helps,
M

**Comment by buratono** [comment]
Hi Martin,
Thank for your prompt reply,
You're correct, I also guess my problem caused by driver/sdk.
I installed pyopencl without any issue, but there was error when I import it,
Now I'm reinstalling driver/sdk,
Thanks for your help,
Tom
