### ISSUE TITLE
offset in 3D data limits accessible color scale

### ISSUE THREAD

**Issue by paulmueller** [maweigert/spimagine#6]
The current master branch [4dad0eaa](https://github.com/maweigert/spimagine/tree/4dad0eaa68c1269a97c3ddc814f055ea37e66faa) has scaling problems when displaying data with offset.

The positions of the contrast/brightness sliders on the left hand side only yield a visible image for a few positions. Otherwise the image is black/full background.

I resolved this temporarily by removing the offset:

```python
data -= data.min()
volfig(0)
volshow(data) 
```

Note: I experienced this problem when working with refractive index values which usually have an offset > 1.0 and don't go beyond 2.

**Comment by maweigert** [comment]
volshow doesn't scale the data to the full range by default, you can however activate that by calling

```python
volshow(data, autoscale = True)
``` 

where data internally is rescaled to a bigger range (via numpy, i.e. possible slow, which is why the default is autoscale=False)

**Comment by paulmueller** [comment]
Thanks.
