### ISSUE TITLE
pip install - not aware of dependency gputools

### ISSUE THREAD

**Issue by VolkerH** [maweigert/spimagine#8]
When running a pip install of spimagine it finishes succesfully, but then complains about gputools missing. 
Running `pip install gputools` fixes this. I'm not familiar with how pip resolves dependencies and whether this can be easily fixed.

**Comment by maweigert** [comment]
There was indeed a missing requirement in setup.py and that was already fixed in the develop branch. So next version upload to pypi will include that. I'll keep the issue open till then. 
Thanks for the notification!

**Comment by VolkerH** [comment]
Cool, thanks

**Comment by maweigert** [comment]
Pypi version is now 0.2.1 - which should include the missing requirement.
Thanks again for pointing that out!
